### PR TITLE
Translations update from Mattermost Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Mattermost Weblate](https://translate.mattermost.com) for [Calls/webapp](https://translate.mattermost.com/projects/calls/webapp/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by ctlaltdieliet — APPROVED** [review]
lgtm :rocket:

**Review by lieut-data — APPROVED** [review]

**Review by ctlaltdieliet — APPROVED** [review]
lgtm!

**Comment by streamer45** [comment]
Need to have a look at why e2e tests are all failing.

**Comment by streamer45** [comment]
It's probably the license thing again, I'll force merge.

**Comment by ctlaltdieliet** [comment]
thank you @streamer45

**Pull request merged**
