### PR TITLE
MM-48336 - Calls: tooltips can get stuck in global widget

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- I couldn't reproduce it, but this should fix it. 

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-48336

### CODE REVIEW

**Comment by streamer45** [comment]
Looks like I can still reproduce on this branch. What I do is I try to screen share and hit cancel on the prompt:


https://user-images.githubusercontent.com/1832946/203437358-698651fb-243e-4de3-9c98-1dcf3acaee29.mp4

**Comment by cpoile** [comment]
@streamer45 Can you try now? I was able to reproduce it, and this finally fixes it for me.

**Review by streamer45 — APPROVED** [review]
Works fine now, thanks :1st_place_medal:

**Pull request merged**
