### PR TITLE
MM-42562 : Add widget link for direct/group channels

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Channel link for GM in widget
image

Channel link for DM in widget
image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42562

### CODE REVIEW

**Review by tanmay-des — APPROVED** [review]
Looks good!

**Review by streamer45 — COMMENTED** [review]
Looks great @M-ZubairAhmed :100: 

One small thing I noticed is that the hover state for long channel names can overlap with the pop out window button. Wondering if we could fix this now since we are here.

overflow

**Comment by M-ZubairAhmed** [comment]
> Looks great @M-ZubairAhmed 💯
> 
> One small thing I noticed is that the hover state for long channel names can overlap with the pop out window button. Wondering if we could fix this now since we are here.


Fixed for both desktop and web 
image

**Review by streamer45 — APPROVED** [review]
Thank you @M-ZubairAhmed :raised_hands:

**Review by cpoile — APPROVED** [review]
Looks great, thanks @M-ZubairAhmed!!

**Pull request merged**
