### PR TITLE
MM-51259 - Emojis in RHS participant list

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Pretty straightforward
- Decided to sort based on reactions, but that is open to opinions (I couldn't tell from the figmas if we were supposed to or not)
- Some resorting of import lines (alphabetical) -- I'm doing this automatically on save now

image

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-51259

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
You are on a roll today :rocket: 

Let's merge it asap so I can merge with the UX changes which will likely affect this.

**Comment by cpoile** [comment]
Hm, guess that isn't working in our repos. 😅

**Comment by streamer45** [comment]
> Hm, guess that isn't working in our repos. sweat_smile

Yeah, I was surprised you even attempted it :laughing:

**Comment by cpoile** [comment]
Sometimes I just like to type things. 

So, we're good to merge then?

**Comment by streamer45** [comment]
> Sometimes I just like to type things.
> 
> So, we're good to merge then?

Can you merge manually against main so it doesn't attempt to run CircleCI?

**Comment by streamer45** [comment]
E2E passed, merging.

**Pull request merged**
