### PR TITLE
MM-54361 - Two cherry picks - #505 and #511 

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Cherry picks #505 and #511 to  release-0.17 branch for a v0.17.1 dot release, to be prepackaged to the 8.0 release.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-54361

### CODE REVIEW

**Comment by cpoile** [comment]
Looks like there's some issues with the recorder -- Jesse ran into a timeout when pressing record during the Dev meeting, he received a timeout after a minute or two. After pressing record a second time we got the confirmation almost instantly.

**Review by streamer45 — APPROVED** [review]

**Comment by streamer45** [comment]
> Looks like there's some issues with the recorder -- Jesse ran into a timeout when pressing record during the Dev meeting, he received a timeout after a minute or two. After pressing record a second time we got the confirmation almost instantly.

Yeah, saw some failures alerts. Will look into it.

**Comment by cpoile** [comment]
@streamer45 Sorry to bug you about it, but can we assume the recording e2e will pass if the recorder was working?

**Comment by streamer45** [comment]
> @streamer45 Sorry to bug you about it, but can we assume the recording e2e will pass if the recorder was working?

We'll have to I think because we made breaking changes which would need us to run a previous `calls-offloader` version to make e2e pass. I can probably run those locally though just to make extra sure.

**Comment by cpoile** [comment]
@streamer45 I think, given these minor changes don't touch anything recording related, we don't need to. I'll merge if you're okay with it.

**Comment by streamer45** [comment]
Alright, it should be safe :+1:

**Pull request merged**
