### PR TITLE
[MM-51852] Update server version to min version that has MM-51852

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- https://github.com/mattermost/mattermost/pull/24731 has a breaking change, and the earliest server branch with that PR is 9.2.0, so make 9.2.0 our new min server version.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-56659

### CODE REVIEW

**Comment by streamer45** [comment]
Wondering if we should bump to latest ESR (v9.5) since we are at it. Most customers would jump to that one when they reach v9.

**Comment by cpoile** [comment]
@streamer45 I thought it was more of a "this is the bare minimum you need" kind of thing, not a "we recommend you be on this ESR for various other reasons." But if you prefer, I don't mind either way.

**Comment by streamer45** [comment]
> @streamer45 I thought it was more of a "this is the bare minimum you need" kind of thing, not a "we recommend you be on this ESR for various other reasons." But if you prefer, I don't mind either way.

That's correct but also have a somewhat important security fix we merged recently (https://github.com/mattermost/mattermost-plugin-calls/pull/620) which doesn't really work before 9.5 either. So maybe there's a chance to align with ESRs going forward.

**Review by streamer45 — APPROVED** [review]
Thanks!

**Pull request merged**
