### PR TITLE
Animation to reaction list

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Ticket Link
Add animation to reaction list

#### Screenshots

https://user-images.githubusercontent.com/28563179/192258255-ceeb91d8-ed78-4c1c-bb03-471454b25573.mp4

### CODE REVIEW

**Review by agarciamontoro — COMMENTED** [review]
This is neat! I've tested it locally and there are times where it's not very smooth:
1. When adding transitions rapidly, there are times where some reactions kind of overlap others. You can see in the first seconds of the video below.
2. When the reactions are disappearing, adding a new one makes the animation quirky. This is shown at the end of the video below.

My knowledge in CSS animations is pretty limited, so I'm afraid I cannot offer much help here, I can just complain :joy: What I thought, though, and sorry if it's a dumb suggestion, is that maybe we can have the new reactions render below the most recent one, but hide them somehow, and then play the animation to push the whole list up. Does that make sense?

[Screencast from 26-09-22 15:17:23.webm](https://user-images.githubusercontent.com/3924815/192286766-990b6019-588c-4111-aa50-c2cbc517ef8c.webm)

**Comment by AGMETEOR** [comment]
> This is neat! I've tested it locally and there are times where it's not very smooth:
> 
> 1. When adding transitions rapidly, there are times where some reactions kind of overlap others. You can see in the first seconds of the video below.
> 2. When the reactions are disappearing, adding a new one makes the animation quirky. This is shown at the end of the video below.
> 
> My knowledge in CSS animations is pretty limited, so I'm afraid I cannot offer much help here, I can just complain 😂 What I thought, though, and sorry if it's a dumb suggestion, is that maybe we can have the new reactions render below the most recent one, but hide them somehow, and then play the animation to push the whole list up. Does that make sense?
> 
>  Screencast.from.26-09-22.15.17.23.webm

@agarciamontoro I am also not very good at them. Was experimenting mostly. But I have delayed the animation time a bit. Mind testing it out again and we see if it improves the animations a bit. Otw, we can always improve this animation in later versions.

**Comment by cyrilzhang-mm** [comment]
I like the idea, but I'm not sure it's possible to make the animation run smoothly using this approach, since every time the component re-renders the animation will reset. So for example when reactions start disappearing, the animation resets, or when a new reaction happens, the animation resets. I think the only way to make the animation smooth is to ensure new reactions only appear after the previous animation has completed.

**Comment by agarciamontoro** [comment]
> we can always improve this animation in later versions with the problem well thought about

I 99% of the time agree with this, but I feel like a quirky animation is not better than no animation at all.

> I think the only way to make the animation smooth is to ensure new reactions only appear after the previous animation has completed.

That would delay new reactions a lot, right? The thing is that people will react in bursts, not steadily through the call, so we need a way of speeding the animation up if new reactions are coming in quickly. I have no idea how to do that, though :nerd_face:

**Comment by AGMETEOR** [comment]
> > I think the only way to make the animation smooth is to ensure new reactions only appear after the previous animation has completed.
> 
> Alright. We can leave this pr here and will take these suggestions and improve it later

**Comment by cpoile** [comment]
Hey @AGMETEOR ! I'll be looking to clean up and merge the contribute branch this week, would you have the bandwidth to take another pass at this at your earliest convenience?

**Comment by AGMETEOR** [comment]
> Hey @AGMETEOR ! I'll be looking to clean up and merge the contribute branch this week, would you have the bandwidth to take another pass at this at your earliest convenience?

Hi @cpoile I don't think I'll have the bandwidth until after next week. This week, I am finishing up some tickets before I head out for leave the whole of next week

**Comment by cpoile** [comment]
@AGMETEOR Ok, thank you Allan!

**Comment by cpoile** [comment]
Thanks @AGMETEOR! If it's okay with you, can we close this for now, and then when it's back on the roadmap I can take a stab at it?

**Pull request closed without merging**
