### PR TITLE
[MM-57365] Stop recording confirmation modal

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Add a stop recording confirmation modal

image

- Designs: https://www.figma.com/design/9HL2HADCQ0lLmn1RBOBGGV/Calls%3A-Recording?node-id=950-32979&m=dev

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-57365

### CODE REVIEW

**Comment by streamer45** [comment]
I assume this is by design, so it's more of a question for @abhijit-singh. I don't see any mention of transcriptions, which is a bit inconsistent with the rest of the related messages.

**Review by streamer45 — APPROVED** [review]
Looks great. Nothing blocking, but I noticed the stop button is not strictly following the latest updates on similar "destructive" buttons in terms of hover and active states and related background/text colors.

**Comment by cpoile** [comment]
Thanks! Fixed the background.

**Review by abhijit-singh — APPROVED** [review]
Looks awesome @cpoile! Thank you!

For the case where transcription is also enabled, we can have the modal say :
Title: Stop recording and transcription
Body: The call recording and transcription files will be processed and posted in the call thread. Are you sure you want to stop the recording and transcription?

image

cc @cwarnermm

**Comment by cpoile** [comment]
Thanks @abhijit-singh, updated with the new text.

**Pull request merged**
