### PR TITLE
Translations update from Mattermost Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Mattermost Weblate](https://translate.mattermost.com) for [Calls/webapp](https://translate.mattermost.com/projects/calls/webapp/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by ctlaltdieliet — APPROVED** [review]
lgtm :rocket:

**Comment by streamer45** [comment]
@mvitale1989 Just checking with you if it's expected for the license to be missing in e2e tests running from forks after the recent fix you sent. Some tests are failing due to that.

**Comment by mvitale1989** [comment]
@streamer45 my fix only changed the `.github/workflows/generate-e2e-report.yml` workflow, the test workers themselves should behave exactly the same I believe

**Comment by mvitale1989** [comment]
It seems like it's the first time the [admin console tests](https://github.com/mattermost/mattermost-plugin-calls/pull/812) run in a Weblate (e.g. last Weblate run was [here](https://github.com/mattermost/mattermost-plugin-calls/pull/836)). So perhaps the tests have always been running without a license, when coming from forks?

**Pull request merged**
