### PR TITLE
MM-44946: Fix: Calls: start trial path from Start Call button not working

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Use the openCloudPricing flow instead of our homegrown trial path because the code changed on webapp/server and broke our flow; it's too late to export the webapp's flow for this, so we're using the CloudPricing modal as a temporary measure to make things work for launch.
- Next step tracked in: https://mattermost.atlassian.net/browse/MM-44992

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-44946

### CODE REVIEW

**Comment by cpoile** [comment]
I'm not able to test this, unfortunately (split.io). So I'll ask for a review now and hope something changes tomorrow, but probably not in the time we have.

**Comment by streamer45** [comment]
> I'm not able to test this, unfortunately (split.io). So I'll ask for a review now and hope something changes tomorrow, but probably not in the time we have. (Do we even have time? I'm unsure whether we can fix this before release.)

We don't have time to include it in 7.0/cloud build but what we can probably do, similarly to other bugs (e.g. the thread autofollow one) we can cut a new release later today, push it to the marketplace and force an update on cloud (through split). That should give us what we want without going through pre-packaging.

**Comment by cpoile** [comment]
@streamer45 Ok, that sounds good, let's do that. 👍

**Comment by streamer45** [comment]
@cpoile Do you want to test this before or after merging?

**Comment by cpoile** [comment]
@streamer45 Do we need to test anything else in this batch? If not, I can cut it from this hash.

**Comment by streamer45** [comment]
@cpoile I think this is the only PR requiring an actual Cloud instance to be verified so I'd say this is it. I don't have to merge anything else for v0.6.1 (or whatever it's going to be).

**Review by streamer45 — APPROVED** [review]

**Pull request merged**
