### PR TITLE
[MM-57421] Live captions e2e tests

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- e2e tests for live captions off + on

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-57421

### CODE REVIEW

**Comment by cpoile** [comment]
@streamer45 This won't work yet of course, but it works locally, so it should work once everything is updated.

**Review by streamer45 — APPROVED** [review]
Nice. Now it's a proper monster test but sadly it can't be avoided.

**Comment by cpoile** [comment]
Yah, I can't see another way around it other than multiple test servers, or some kind of lock (for the duration of updating settings and starting a call)...

**Comment by streamer45** [comment]
@cpoile Can be merged.

**Comment by cpoile** [comment]
@streamer45 Was looking at making a lock for concurrent tests, but it looks like they purposefully make that kind of thing very difficult. Will try again later.

**Comment by streamer45** [comment]
> @streamer45 Was looking at making a lock for concurrent tests, but it looks like they purposefully make that kind of thing very difficult. Will try again later.

Yeah good luck with that https://github.com/microsoft/playwright/issues/21484

**Pull request merged**
