### PR TITLE
Fix linter errors

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- I run `make test && make check-style && make i18n-extract` before committing, and it looks like something changed and made `golangci-lint` more strict. Now `make check-style` will complete locally.

#### Ticket Link
- none

### CODE REVIEW

**Comment by streamer45** [comment]
These are usually caused by bumping the local version of `golangci-lint`. I was actually handling them in https://github.com/mattermost/mattermost-plugin-calls/pull/460 which is also bumping the version to run on CI.

**Comment by cpoile** [comment]
@streamer45 It looks like I bumped past where you are, mine is `1.54.2` and is catching a few more.

**Comment by streamer45** [comment]
@cpoile Right, it's been a while since I started that PR. Any objections on updating that? It's pretty much ready to be merged anyway, been testing on Community for a couple of weeks now.

**Comment by cpoile** [comment]
@streamer45 Ok, done, closing this.

**Pull request closed without merging**
