### PR TITLE
Improve joined users widget notification

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR reworks the (now broken) abysmal logic to show the notification pill for recently joined participants. 
Still the CSS animation could use some improvements but that's a bit more tricky and will need some figuring out.

### CODE REVIEW

**Review by cpoile — COMMENTED** [review]
Awesome, it fixes the joining notification never firing problem.
But there's some issues with desktop -- 
1. on joining you get the previous joined members appearing as if they had just joined, and 
2. the v spacing is a bit off with the muted notification:

Actually, that happens on webapp as well: 
image

**Comment by streamer45** [comment]
Thanks @cpoile, could you give it another go?

**Review by cpoile — APPROVED** [review]
Nice!

Two nits (don't need to be fixed if it's tough):
There's still some spacing issues with the muted notification on Chrome (not on Firefox, for a first). 
image

And if you join right after person A (before the Person A's join has been removed), you'll get  person A's notification of course, but I don't think that's a big deal. (You could think of that as almost like a feature, to see who had joined "right around the same time" as you did.)

**Comment by streamer45** [comment]
> There's still some spacing issues with the muted notification on Chrome (not on Firefox, for a first).

@cpoile Did you refresh your cache? I don't see that but I suspect it may be some outdated CSS lingering.

> if you join right after person A (before the Person A's join has been removed), you'll get person A's notification of course

Mmm, that sounds like a potential race but I am not overly worried given the use case.

**Comment by cpoile** [comment]
> @cpoile Did you refresh your cache? I don't see that but I suspect it may be some outdated CSS lingering.

Indeed it was, works great now, thanks!

> Mmm, that sounds like a potential race but I am not overly worried given the use case.

👍

**Pull request merged**
