### PR TITLE
Translations update from Mattermost Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Mattermost Weblate](https://translate.mattermost.com) for [Calls/webapp](https://translate.mattermost.com/projects/calls/webapp/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by ctlaltdieliet — APPROVED** [review]
lgtm

**Comment by streamer45** [comment]
@toninis E2E pipeline is failing here but my expectation is that after https://github.com/mattermost/mattermost-plugin-calls/pull/757 it should be working from forks. Thoughts?

**Comment by streamer45** [comment]
> @streamer45 There are 2 failed tests for the e2e testing . I added the report summary as required in order to wait for the e2e tests upon PR . In the meanwhile we can always make the status check success and judge on the failed tests if it's ok to merge . WDYT ?

@toninis Yeah, I'd prefer if we kept the ability to merge as sometimes we may have some flakiness or regressions on the web app side that have nothing to do with Calls.

**Comment by toninis** [comment]
Closing in favor of https://github.com/mattermost/mattermost-plugin-calls/pull/797

**Comment by toninis** [comment]
Closing in favor of https://github.com/mattermost/mattermost-plugin-calls/pull/797

**Pull request closed without merging**
