### PR TITLE
[MM-47182] Call recordings

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR to merge the feature branch.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-47182

### CODE REVIEW

**Comment by streamer45** [comment]
@tanmay-des Given it's a bit tricky to get recordings working locally as it requires the service to be configured and running I've prepared a test server you can use to try this out:

https://calls.test.mattermost.cloud/

Account Type | Username | Password
-- | -- | --
Admin | sysadmin | Sys@dmin-sample1
User | user-1 | User-1@123

**Comment by tanmay-des** [comment]
Great work @streamer45!
I played around with it and functionality wise i think it's working fine!
_Though I have not able to try leaving a call in between while there are multiple members, and witness the host change. Do we have a notice for that?_

Other than that I have made a quick list for small [UI Polish](https://www.figma.com/file/9HL2HADCQ0lLmn1RBOBGGV/Calls%3A-Recording?node-id=298%3A120956&t=oYOvnsJOrFlbG3VL-1) (Which are just bunch of good to haves only!)

**Comment by streamer45** [comment]
@cpoile I merged the GA changes and updated the test server. Please give it a quick pass to make sure nothing major got broken in the process. 

@tanmay-des Your feedback should be addressed. Please give it a second pass when you get a chance and let me know.

Thank you!

**Review by tanmay-des — APPROVED** [review]
Looks good to me!

**Comment by streamer45** [comment]
Going to merge this as soon as CI passes to unblock release. Thanks everyone for effort you put into this :tada:

**Pull request merged**
