### PR TITLE
MM-47046 Use version of React DOM provided by web app

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- (From @hmhealey): For some more context, see [here](https://community.mattermost.com/core/pl/1fkkx7pj1jrwffrc6drh3x71eh). The short version though is that we updated the web app to React 17, and there's a chance that plugins will have some issues with it because they're compiled with the React 16 version of ReactDOM.
- Upgrading the dependencies that we use from webapp ("externals")
- tested it locally on an up-to-date master

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47046

#### Related Pull Requests
https://github.com/mattermost/mattermost-plugin-playbooks/pull/1489
https://github.com/mattermost/mattermost-plugin-todo/pull/190
https://github.com/mattermost/focalboard/pull/3861

### CODE REVIEW

**Comment by streamer45** [comment]
Thanks. I assume this can safely go in the next version (shipping with 7.4)?

**Comment by cpoile** [comment]
@streamer45 Yep, 7.4

**Review by streamer45 — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by cpoile** [comment]
@streamer45 We can merge this if we want to upgrade to react 17. @hmhealey mentioned it likely wouldn't break anything since focalboard has been on React 17 for awhile already.

**Comment by streamer45** [comment]
Thanks @cpoile , then let's merge it now so we get some time to test it on community (starting tomorrow most likely).

**Pull request merged**
